[package]
name = "esfxr-dsp"
version = "0.0.0"
authors = ["Denis BOURGE <bourge.denis@gmail.com>"]
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
esfxr-audio-driver = { path = "../esfxr-audio-driver" }
fundsp = "0.13.0"
tracing = "0.1.37"
